//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Priceio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Cajero : global::System.Configuration.ApplicationSettingsBase {
        
        private static Cajero defaultInstance = ((Cajero)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Cajero())));
        
        public static Cajero Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9101")]
        public int PuertoTCP {
            get {
                return ((int)(this["PuertoTCP"]));
            }
            set {
                this["PuertoTCP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ValorLogPago {
            get {
                return ((string)(this["ValorLogPago"]));
            }
            set {
                this["ValorLogPago"] = value;
            }
        }
    }
}
