//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Priceio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class ESP_MX_ : global::System.Configuration.ApplicationSettingsBase {
        
        private static ESP_MX_ defaultInstance = ((ESP_MX_)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ESP_MX_())));
        
        public static ESP_MX_ Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Archivo")]
        public string Archivo {
            get {
                return ((string)(this["Archivo"]));
            }
            set {
                this["Archivo"] = value;
            }
        }
    }
}
