<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>ICONO.ico</ApplicationIcon>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ColorSwatchCircle.png" />
    <None Remove="ColorSwatchSquare1.png" />
    <None Remove="ColorSwatchSquare2.png" />
    <None Remove="ICONO.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ICONO.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Recursos\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1938.49" />
    <PackageReference Include="System.Data.Odbc" Version="7.0.0" />
    <PackageReference Include="System.Management" Version="7.0.2" />
    <PackageReference Include="System.Speech" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DataGate">
      <HintPath>bin\x86\Debug\net6.0-windows\DataGate.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ColorSwatchCircle.png" />
    <Resource Include="ColorSwatchSquare1.png" />
    <Resource Include="ColorSwatchSquare2.png" />
    <Resource Include="ICONO.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ConfigurarNombres.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="ConfigurarVoz.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="PropiedadesBordeTurnero.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="PropiedadesLabelTurno.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="PropiedadesWEB.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="PropiedadesMultimediaTurno.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="ConfigurarVoz.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>


</Project>
