<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="logo dibal.png" />
    <None Remove="metin mapa.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Recursos\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="logo dibal.png" />
    <Resource Include="metin mapa.jpg" />
  </ItemGroup>

</Project>
