<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ColorSwatchCircle.png" />
    <None Remove="ColorSwatchSquare1.png" />
    <None Remove="ColorSwatchSquare2.png" />
    <None Remove="logo.png" />
    <None Remove="logoapp.png" />
    <None Remove="Recursos\logo.png" />
    <None Remove="Recursos\logoapp.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2210.55" />
    <PackageReference Include="MySql.Data" Version="8.3.0" />
    <PackageReference Include="System.Data.Odbc" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DataGate">
      <HintPath>..\..\DataGate\DataGate\bin\Release\netstandard2.0\DataGate.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ColorSwatchCircle.png" />
    <Resource Include="ColorSwatchSquare1.png" />
    <Resource Include="ColorSwatchSquare2.png" />
    <Resource Include="logo.png" />
    <Resource Include="logoapp.png" />
    <Resource Include="Recursos\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Recursos\logoapp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ConfigurarNombres.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="ConfigurarVoz.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="PropiedadesBordeTurnero.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="PropiedadesLabelTurno.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="PropiedadesWEB.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="PropiedadesMultimediaTurno.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Recursos\audios\bells-1.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\bells-logo.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\call-to-attention.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\ding.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\doorbell2.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\horn-hooter.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\jsyd_klaxon2.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\new-notification.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\news-ting.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\reception-bell.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\red-alert-klaxon.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\service-bell-ring.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\siren-alert.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\soft-piano-logo.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\vuvuzela.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\controlTurno.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\icono.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\nombreEquipos.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\turnoAnt.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\voz.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="ConfigurarVoz.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>


</Project>
