<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <Platforms>AnyCPU;x86</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ColorSwatchCircle.png" />
    <None Remove="ColorSwatchSquare1.png" />
    <None Remove="ColorSwatchSquare2.png" />
    <None Remove="logo.png" />
    <None Remove="logoapp.png" />
    <None Remove="logoPriceio.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.1" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2210.55" />
    <PackageReference Include="MySql.Data" Version="9.0.0" />
    <PackageReference Include="System.Data.Odbc" Version="8.0.1" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.Speech" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DataGate">
      <HintPath>DataGate.dll</HintPath>
    </Reference>
    <Reference Include="ITLlib">
      <HintPath>ITLlib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ColorSwatchCircle.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="ColorSwatchSquare1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="ColorSwatchSquare2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="logoapp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="logoPriceio.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="VentanasGenericas\ConfigurarNombres.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="VentanasGenericas\ConfigurarVoz.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="VentanasPropiedadesSplash\PropiedadesImpresora.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="VentanasPropiedadesSplash\PropiedadesVentanaSplash.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="VentanasPropiedadesSplash\PropiedadesLabelTurno.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="VentanasPropiedadesPrincipal\PropiedadesWEB.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="VentanasPropiedadesSplash\PropiedadesMultimediaTurno.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="DataGate.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ITLlib.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <None Update="Recursos\audios\bells-1.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\bells-logo.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\call-to-attention.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\ding.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\doorbell2.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\horn-hooter.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\jsyd_klaxon2.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\new-notification.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\news-ting.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\reception-bell.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\red-alert-klaxon.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\service-bell-ring.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\siren-alert.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\soft-piano-logo.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\audios\vuvuzela.wav">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\ColorSwatchCircle.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\ColorSwatchSquare1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\ColorSwatchSquare2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\controlTurno.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\ICONO.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\logoapp.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\logoPriceio.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\nombreEquipos.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\pictureAdd.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\server.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\turnoAnt.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Recursos\voz.3k">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="VentanasGenericas\ConfigurarVoz.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>


</Project>
